//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SVIEN
    {
        public int ID { get; set; }
        public int MANGANH { get; set; }
        public string MASV { get; set; }
        public string TENSV { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> CMND { get; set; }
        public string QUEQUAN { get; set; }
        public string DIACHI { get; set; }
    
        public virtual NGANH NGANH { get; set; }
    }
}
