//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SVIEN()
        {
            this.DIEMs = new HashSet<DIEM>();
        }
    
        public int MASV { get; set; }
        public string TENSV { get; set; }
        public Nullable<int> MALOP { get; set; }
        public Nullable<int> MAKHOA { get; set; }
        public Nullable<bool> GTINH { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public Nullable<int> SDT { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
    
        public virtual KHOA KHOA { get; set; }
        public virtual LOP LOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEM> DIEMs { get; set; }
    }
}
